apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-ui-dashboard-test
spec:
  selector:
    matchLabels:
      app: ts-ui-dashboard-test
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-ui-dashboard-test
    spec:
      containers:
      - name: ts-ui-dashboard-test
        image: youyoumubei/ts-ui-dashboard-test:1.9
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 500Mi

---

apiVersion: v1
kind: Service
metadata:
  name: ts-ui-dashboard-test
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      nodePort: 32678
  selector:
   app: ts-ui-dashboard-test
---
